accounts/urls.py
from django.urls import path
from .views import SignupPageView

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignupPageView.as_view(), name='signup'),
]

profiles/urls.py
from django.urls import path

from .views import (ProfileDetailView, ProfileUpdateView, ProfileListView,
                    ProfileCreateView, ProfileDeleteView, ProfileResultsListView
                    )

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='profile_list'),
    path('<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('search/', ProfileResultsListView.as_view(), name='search_results'),

    path('edit/<int:pk>/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('delete/<int:pk>/delete/', ProfileDeleteView.as_view(), name='profile_delete'),
    path('new/', ProfileCreateView.as_view(), name='profile_new'),
]

projects/urls.py
from django.urls import path
from .views import (
    ProjectListView, ProjectDetailView, ProjectUpdateView,
    ProjectDeleteView,
    ProjectCreateView,
    SearchResultsListView,
)

# app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='project_list'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('search/', SearchResultsListView.as_view(), name='search_results'),

    path('<int:pk>/edit/', ProjectUpdateView.as_view(), name='project_edit'),
    path('<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('new/', ProjectCreateView.as_view(), name='project_new'),
]

urls.py
from django.urls import path

from .views import HomePageView, AboutPageView


urlpatterns = [
    path('about/', AboutPageView.as_view(), name='about'),
    path('', HomePageView.as_view(), name='home'),

]

models.py
from django.db import models

profiles/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Profile(models.Model):
    first_name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    description = models.TextField()
    profile_images = models.ImageField(upload_to='profile_images/', blank=True)

    class Meta:
        permissions = [
            ('special status', 'can read profile')
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.title = None

    def get_absolute_url(self):
        return reverse('profiles:profile_detail', args=[str(self.id)])

accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm


class SignupPageView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'account/signup.html'

profiles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView

from .models import Profile


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    context_object_name = 'profile_list'
    template_name = 'profiles/profile_list.html'
    login_url = 'profile_login'


class ProfileDetailView(LoginRequiredMixin,
                        PermissionRequiredMixin,
                        DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'profiles/profile_detail.html'
    login_url = 'profile_login'
    permission_required = 'profiles.special_status'


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = {'first_name', 'description'}
    template_name = 'profiles/profile_edit.html'
    success_msg = 'Profile Updated'


class ProfileDeleteView(DeleteView):
    model = Profile
    template_name = 'profiles/profile_delete.html'
    success_url = reverse_lazy('profile_list')


class ProfileCreateView(CreateView):
    model = Profile
    template_name = 'profiles/profile_new.html'
    fields = ('first_name', 'location', 'description')


class ProfileResultsListView(ListView):
    model = Profile
    context_object_name = 'profile_list'
    template_name = 'profiles/profile_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Profile.objects.filter(
            Q(title__icontains=query) | Q(author__icontains=query)
        )

views.py
from django.views.generic import TemplateView, FormView



class HomePageView(TemplateView):
    template_name = 'home.html'


class AboutPageView(TemplateView):
    template_name = 'about.html'

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}KodePal{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
  <header>
    <!-- Fixed navbar -->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4
     mb-3 bg-white border-bottom shadow-sm">
      <a  href="{% url 'home' %}" class="navbar-brand my-0 mr-md-auto
      font-weight-normal">KodePal</a>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'about' %}">About</a>
        <a class="p-2 text-dark" href="{% url 'profiles:profile_list' %}">Find a KodePal</a>
        <a class="p-2 text-dark" href="{% url 'profiles:profile_new' %}">Create a profile</a>

        {% if user.is_authenticated %}
            <ul class="p-2 text-dark navbar-nav mr-auto">
            <li class="nav-item"><a href="{% url 'project_new' %}">Post a project</a></li>

            </ul>
            <ul class="p-2 text-dark navbar-nav mr-auto">
                <li class="nav-item"><a href="{% url 'project_list' %}">Current Projects</a></li>
            </ul>
{#            <ul class="p-2 text-dark navbar-nav mr-auto">#}
{#                <li class="nav-item"><a href="{% url 'profiles:profile_list' %}">KodePal's</a></li>#}
{#            </ul>#}

          <a class="p-2 text-dark" href="{% url 'account_logout' %}">Log Out</a>
        {% else %}
          <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
          <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Sign Up</a>
  {% endif %}
</nav>
    </div>
  </header>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <!-- JavaScript -->
  <script src="{% static 'js/base.js' %}"></script>
  <!-- JS, Popper.js, and jQuery -->

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>

</body>
</html>

templates/about.html
{% extends '_base.html' %}

{% block title %}Our Story{% endblock title %}

{% block content %}
    <h1>About Page</h1>
    <p>It has been quite a journey!</p>
    <p>Join us!</p>
{% endblock content %}

templates/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
  <h1>Help us take the loneliness out of tech!!</h1>
  {% if user.is_authenticated %}
    <p>Welcome {{ user.email }}!</p>
{#      <form class="form-inline mt-2 mt-md-0" action="{% url 'search_results'%}"#}
{#            method="get">#}
{#      <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">#}
{#      </form>#}
      <img class="palette" src="{% static 'images/color_pallete.png' %}" alt="colors">
    <!--<p><a href="{% url 'account_logout' %}">Log Out</a></p> -->
  {% else %}
    <p>You are not logged in</p>
    <p><a href="{% url 'account_login' %}">Log In</a> |
    <a href="{% url 'account_signup' %}">Sign Up</a></p>

  {% endif %}
{% endblock content %}

templates/profiles/profile_delete.html
{% extends '_base.html' %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ profile.first_name }}"?</p>
        <button class="btn btn-danger ml-2"
                type="submit" value="Save">Confirm</button>
    </form>
{% endblock content %}

templates/profiles/profile_detail.html
{% extends '_base.html' %}

{% block title %}{{ profile.first_name }}{% endblock title %}

{% block content %}
    <div class="profile-detail">
    {% if profile.profile_images %}
    <img class="profile_images" src="{{ profile.profile_images.url }}" alt="{{ profile.first_name }}">
    {% endif %}
        <h2><a href="">{{ profile.get_absolute_url}}</a></h2>
        <p>First_name: {{ profile.first_name }}</p>
        <p>Description: {{ profile.description }}</p>

        </div>
{% endblock content %}

templates/profiles/profile_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/profiles/profile_list.html
{% extends '_base.html' %}

{% block title %}Profiles{% endblock title %}

{% block content %}
    {% for profile in profile_list %}
    <div>

        <h2><a href="{{ profile.get_absolute_url }}">{{ profile.description }}</a></h2>

        </div>
    {% endfor %}
{% endblock content %}

<h1>Profiles???</h1>
<h2>Testing</h2>

templates/profiles/profile_new.html
{% extends '_base.html' %}

{% block content %}
    <h1>Profile</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success ml-2"
                type="submit">Save</button>
    </form>
{% endblock content %}

templates/profiles/profile_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/projects/project_delete.html
{% extends '_base.html' %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ project.title }}"?</p>
        <button class="btn btn-danger ml-2"
                type="submit" value="Save">Confirm</button>
    </form>
{% endblock content %}

templates/projects/project_detail.html
{% extends '_base.html' %}

{% block title %}{{ project.title }}{% endblock title %}

{% block content %}
    <div class="project-detail">
    {% if project.cover %}
    <img class="projectcover" src="{{ project.cover.url }}" alt="{{ project.title }}">
    {% endif %}
        <h2><a href="">{{ project.title }}</a></h2>
        <p>Author: {{ project.author }}</p>
        <p>Description: {{ project.description }}</p>

        <div>
        <h3>Reviews</h3>
            <ul>
                {% for review in project.reviews.all %}
                    <li>{{ review.review }} ({{ review.author }})</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <p><a href="{% url 'project_edit' project.pk %}">Edit your Project</a></p>
    <p>Back to <a href="{% url 'project_list' %}">All projects</a></p>
{% endblock content %}

templates/projects/project_edit.html
<{% extends '_base.html' %}

{% block content %}
    <h1>Edit</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info ml-2"
                type="submit" value="Save">Update</button>
    </form>
{% endblock content %}

templates/projects/project_list.html
{% extends '_base.html' %}

{% block title %}Projects looking for KodePal's{% endblock title %}

{% block content %}
    {% for project in project_list %}
    <div>
        <h2><a href="{{ project.get_absolute_url }}">{{ project.title }}</a></h2>


        </div>
    {% endfor %}
{% endblock content %}

templates/projects/project_new.html
{% extends '_base.html' %}

{% block content %}
    <h1>New Project</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success ml-2"
                type="submit">Save</button>
    </form>
{% endblock content %}

templates/projects/search_results.html
{% extends '_base.html' %}

{% block title %}Search{% endblock title %}

{% block content %}
    <h1>Search Results</h1>
    {% for project in project_list %}
    <div>

        <h3><a href="{{ project.get_absolute_url }}">{{ project.title }}</a></h3>
        <p>Author: {{ project.author }}</p>
        <p>Description: {{ project.description }}</p>
    </div>
    {% endfor %}
{% endblock content %}